// Real Wordle-quality word list
// ANSWER_WORDS: ~800+ common curated answer words (real English, good for guessing game)
// VALID_WORDS:  All answer words + extra valid guesses (~1200+ total)
// Based on structure of original NYT Wordle word lists

const ANSWER_WORDS = [
  // A
  "ABACK","ABAFT","ABASE","ABASH","ABATE","ABBEY","ABBOT","ABHOR","ABIDE","ABODE",
  "ABORT","ABUSE","ABYSS","ACORN","ACRID","ACUTE","ADAGE","ADEPT","ADMIT","ADOBE",
  "ADOPT","ADORE","ADORN","ADULT","AEGIS","AFOOT","AFTER","AGAIN","AGATE","AGAVE",
  "AGILE","AGING","AGLOW","AGONY","AGREE","AHEAD","AISLE","ALBUM","ALDER","ALLAY",
  "ALOOF","ALOUD","ALPHA","ALTAR","ALTER","AMASS","AMAZE","AMBLE","AMEND","AMINO",
  "AMONG","AMPLE","AMUSE","ANGEL","ANGER","ANGLE","ANGRY","ANIME","ANNEX","ANTIC",
  "ANVIL","AORTA","APART","APHID","APPLE","APPLY","APRON","APTLY","ARBOR","ARDOR",
  "ARENA","ARGUE","ARISE","ARMOR","AROMA","AROSE","ARRAY","ASIDE","ATLAS","ATONE",
  "ATTIC","AUDIO","AUDIT","AUGUR","AVAIL","AVIAN","AVOID","AWASH","AWFUL","AWOKE",
  "AZURE",
  // B
  "BADGE","BADLY","BAGEL","BAGGY","BAIZE","BANAL","BANJO","BASTE","BATCH","BEACH",
  "BEARD","BEAST","BEECH","BEFIT","BEGAN","BEGIN","BEING","BELLE","BELLY","BENCH",
  "BERTH","BESET","BEVEL","BIBLE","BINGE","BIOME","BIRCH","BIRTH","BISON","BLACK",
  "BLADE","BLAME","BLAND","BLANK","BLAST","BLAZE","BLEAK","BLEAT","BLEED","BLEND",
  "BLESS","BLIMP","BLIND","BLISS","BLOAT","BLOCK","BLOOD","BLOOM","BLOWN","BLUES",
  "BLUFF","BLUNT","BLURB","BLURT","BLUSH","BONUS","BOUND","BRACE","BRAIN","BRASH",
  "BRAWN","BREAD","BREAK","BREED","BRIDE","BRISK","BROAD","BROIL","BROOD","BROOK",
  "BROTH","BROWN","BRUNT","BRUTE","BUGGY","BUILD","BUILT","BULKY","BULLY","BUMPY",
  "BUNCH","BUNNY","BURST",
  // C
  "CABIN","CAMEL","CANDY","CANNY","CARGO","CARRY","CARVE","CAUSE","CEASE","CHAIN",
  "CHAIR","CHALK","CHAMP","CHAOS","CHARM","CHART","CHASE","CHEAP","CHEAT","CHECK",
  "CHEEK","CHEER","CHESS","CHEST","CHIEF","CHILD","CHINA","CHOIR","CHOKE","CHOSE",
  "CHUNK","CIVIC","CIVIL","CLAIM","CLAMP","CLASH","CLASS","CLEAN","CLEAR","CLERK",
  "CLIFF","CLIMB","CLING","CLOSE","CLOUD","COMET","COMIC","COMMA","CONCH","CORAL",
  "COULD","COUNT","COURT","COVER","CRACK","CRAFT","CRANE","CRASH","CREAK","CREAM",
  "CREED","CREEK","CREEP","CRIMP","CRISP","CROAK","CROSS","CROWD","CROWN","CRUMB",
  "CRUSH","CRUST","CRYPT","CURLY","CURRY","CURSE","CYCLE",
  // D
  "DADDY","DAILY","DAISY","DANCE","DATUM","DECAL","DECOY","DELVE","DEPOT","DEPTH",
  "DERBY","DIRTY","DISCO","DITCH","DIZZY","DODGE","DOING","DOUBT","DOUGH","DOWDY",
  "DRAFT","DRAIN","DRANK","DRAWL","DRAWN","DREAD","DREAM","DRILL","DRINK","DRIVE",
  "DRONE","DROVE","DROWN","DRUNK","DRYER","DUCHY","DUNCE","DWARF","DYING",
  // E
  "EAGER","EARLY","EARTH","EBONY","EIGHT","ELITE","EMPTY","ENEMY","ENJOY","ENSUE",
  "ENTER","ENTRY","EQUAL","ERROR","ESSAY","ETUDE","EVADE","EVERY","EXACT","EXERT",
  "EXILE","EXTRA","EXULT",
  // F
  "FABLE","FAINT","FAITH","FALSE","FANCY","FAUNA","FEAST","FEIGN","FENCE","FERAL",
  "FETCH","FEVER","FIELD","FIFTH","FIFTY","FINCH","FIRST","FIXED","FJORD","FLAME",
  "FLANK","FLARE","FLASK","FLECK","FLEET","FLESH","FLINT","FLOAT","FLOOD","FLOOR",
  "FLORA","FLOUR","FLUFF","FLUKE","FLUNG","FLUTE","FOCUS","FORGE","FORGO","FORTE",
  "FOYER","FRAIL","FRAME","FREED","FRESH","FRILL","FROZE","FROND","FROST","FROTH",
  "FROWN","FUGUE","FULLY","FUNGI","FUNKY","FUNNY",
  // G
  "GAUDY","GAUZE","GAVEL","GHOST","GIDDY","GIVEN","GIZMO","GLARE","GLEAN","GLIDE",
  "GLOOM","GLOSS","GNASH","GODLY","GORGE","GOUGE","GOURD","GRACE","GRADE","GRAIN",
  "GRASP","GRATE","GRAZE","GREET","GRIEF","GRIND","GROAN","GROIN","GROSS","GROUP",
  "GROUT","GRUFF","GRUNT","GUILE","GUISE","GULCH","GUSTO","GYPSY",
  // H
  "HABIT","HAPPY","HARSH","HASTY","HAVEN","HEIST","HELIX","HENCE","HERON","HILLY",
  "HITCH","HOARD","HOARY","HOLLY","HOMER","HONEY","HONOR","HORDE","HORSE","HOTEL",
  "HOUND","HUMAN","HUMPH","HUMUS","HUNCH","HURRY","HYENA",
  // I
  "ICILY","ICING","IDEAL","IDIOM","IGLOO","IMPLY","INANE","INCUR","IRATE","IRONY",
  "ITCHY",
  // J
  "JAUNT","JAZZY","JELLY","JEWEL","JIFFY","JOUST","JUMBO","JUMPY","JUROR",
  // K
  "KNACK","KNAVE","KNEEL","KNELT","KNIFE","KNOCK","KNOWN",
  // L
  "LANCE","LAPEL","LAPSE","LATCH","LATHE","LAYER","LEAPT","LEARN","LEECH","LEERY",
  "LEGAL","LETUP","LEVEL","LIGHT","LIVER","LLAMA","LOATH","LODGE","LOFTY","LOGIC",
  "LOWLY","LOYAL","LUCKY","LUMEN","LUNGE","LURCH","LUSTY","LYING",
  // M
  "MAGIC","MAMBO","MANGO","MANOR","MAPLE","MARCH","MARRY","MARSH","MATCH","MAXIM",
  "MAYOR","MELEE","MERCY","MERGE","MERIT","MERRY","MESSY","METRO","MIDST","MIGHT",
  "MIMIC","MINCE","MIRTH","MISER","MITRE","MIXED","MOCHA","MODEL","MOGUL","MOIST",
  "MONEY","MONTH","MOOSE","MORPH","MOURN","MUDDY","MULCH","MUMMY","MURAL","MURKY",
  "MUSHY","MUSTY","MYRRH",
  // N
  "NADIR","NAIVE","NASTY","NAVAL","NIFTY","NIGHT","NOBLE","NOISE","NOTCH","NOVEL",
  "NYMPH",
  // O
  "OCCUR","OFFAL","OFTEN","OMEGA","ONION","ONSET","OPTIC","ORBIT","ORDER","OTTER",
  "OUTDO","OVOID","OXIDE",
  // P
  "PAINT","PANSY","PAPAL","PAPER","PARTY","PASTA","PATCH","PAUSE","PEACE","PEARL",
  "PENAL","PERCH","PERKY","PESKY","PETTY","PHASE","PHONE","PHOTO","PIANO","PILOT",
  "PINEY","PIQUE","PIXEL","PIXIE","PLACE","PLAIN","PLANT","PLATE","PLEAD","PLEAT",
  "PLUCK","PLUMB","PLUME","PLUNK","PLUSH","POACH","POWER","PRANK","PRAWN","PRESS",
  "PRICE","PRICK","PRIME","PRISM","PRIVY","PROBE","PRONE","PROOF","PROSE","PROUD",
  "PROWL","PRUDE","PRUNE","PSALM","PUDGY","PUNCH","PUPIL","PURSE",
  // Q
  "QUALM","QUASH","QUEEN","QUELL","QUERY","QUEUE","QUICK","QUIET","QUIRK","QUOTA",
  "QUITE",
  // R
  "RABBI","RADAR","RAINY","RALLY","RAMEN","RANDY","RATTY","RAVEN","REGAL","REIGN",
  "RELAX","RELAY","RENEW","REPAY","REPEL","RESIN","RETRO","RETRY","REVEL","RIDER",
  "RIDGE","RIFLE","RIGHT","RIGOR","RISKY","RITZY","RIVET","RIVAL","ROBIN","ROBOT",
  "ROCKY","ROGUE","ROUGE","ROUGH","ROWDY","ROYAL","RUDDY","RULER","RUMMY","RUPEE",
  "RUSTY",
  // S
  "SAINT","SALSA","SALTY","SALVO","SANDY","SASSY","SAUCE","SAUCY","SAVOR","SCALD",
  "SCALP","SCANT","SCARE","SCARF","SCENE","SCOFF","SCOLD","SCONE","SCOOP","SCOPE",
  "SCORN","SCOUR","SCOWL","SCRAM","SCRAP","SCRUB","SEEDY","SEIZE","SENSE","SERVE",
  "SETUP","SEVEN","SHADE","SHAKE","SHAKY","SHALL","SHAME","SHARE","SHARK","SHARP",
  "SHAWL","SHEEN","SHEER","SHEET","SHELF","SHELL","SHIFT","SHINY","SHONE","SHOOK",
  "SHOUT","SHRUG","SIGMA","SILLY","SINCE","SIXTH","SIXTY","SKILL","SKIMP","SKIRT",
  "SKULL","SKUNK","SLANT","SLASH","SLAVE","SLEEK","SLEET","SLICK","SLIDE","SLIME",
  "SLIMY","SLOSH","SLOTH","SLUMP","SMALL","SMART","SMEAR","SMILE","SMITE","SMOCK",
  "SMOKE","SMOTE","SNACK","SNARE","SNARL","SNEAK","SNIFF","SNORE","SNORT","SNOUT",
  "SNOWY","SNUCK","SOBER","SOLAR","SOLVE","SONIC","SORRY","SOUTH","SPACE","SPARE",
  "SPARK","SPECK","SPELL","SPEND","SPICE","SPILL","SPINE","SPITE","SPOKE","SPOOK",
  "SPORE","SPORT","SPOUT","SPREE","SPURN","SPURT","STACK","STAGE","STAID","STAIN",
  "STALE","STALK","STALL","STAMP","STAND","STANK","STARE","STARK","STASH","STEAL",
  "STEAM","STEEL","STEEP","STEER","STERN","STIFF","STILL","STOIC","STONE","STOOD",
  "STORK","STORM","STORY","STOUT","STRAY","STRIP","STUCK","STUDY","STUFF","STUNK",
  "STUNT","SUGAR","SUPER","SURGE","SWAMP","SWARD","SWATH","SWEAR","SWEAT","SWEEP",
  "SWEET","SWELL","SWIFT","SWILL","SWIPE","SWIRL","SWORD","SWORE","SWUNG",
  // T
  "TABBY","TAPIR","TAUNT","TAWNY","TERSE","THANE","THANK","THEFT","THEME","THOSE",
  "THROW","TIMID","TIPSY","TONIC","TORSO","TOXIC","TRACE","TRACK","TRADE","TRAIL",
  "TRAIN","TRAMP","TRASH","TRAWL","TREAD","TREND","TRIAD","TRIBE","TRICK","TRIED",
  "TRIPE","TRITE","TROLL","TROUT","TROVE","TRUCE","TRUCK","TRULY","TRUMP","TRUNK",
  "TRYST","TULIP","TWANG","TWICE","TWILL","TWINE","TWIRL",
  // U
  "UDDER","ULCER","ULTRA","UNCLE","UNDUE","UNFIT","UNTIL","UNZIP","UPPER","UPSET",
  "URBAN","USHER","USURP","UTTER",
  // V
  "VALID","VALUE","VAULT","VAPOR","VERSE","VICAR","VIGIL","VIRAL","VIPER","VIVID",
  "VODKA","VOILA","VOUCH","VYING",
  // W
  "WALTZ","WASTE","WATCH","WATER","WEARY","WEAVE","WEDGE","WEIRD","WIELD","WIMPY",
  "WITCH","WITTY","WRATH","WRING","WRIST","WRONG",
  // Y
  "YEARN","YEAST","YOUNG","YOUTH","YUMMY",
  // Z
  "ZESTY","ZIPPY",
]

// Extra valid guess words (not used as answers but accepted as guesses)
const EXTRA_VALID = [
  "AAHED","AALII","ABACI","ABEAM","ABETS","ABLER","ABRAY","ABYSM","ACMES","ACNED",
  "ACNES","ACRES","ACTIN","ACTED","ACTON","ADDED","ADDER","ADEEM","ADMEN","ADOWN",
  "ADZES","AEONS","AERIE","AFOUL","AFRIT","AGENE","AGIOS","AGISM","AGIST","AGMAS",
  "AGONE","AGONS","AGUED","AHOLD","AIOLI","AIRED","AIRER","AKELA","AKENE","ALANE",
  "ALARM","ALOFT","ALULA","ALUMS","AMISS","AMITY","AMPLY","ANKHS","ANNUL","ANONS",
  "APIAN","ARCED","ARRAS","ARROW","ASHEN","ASKER","ASPEN","ATILT","ATMAN","ATOLL",
  "ATOMS","ATONY","ATOPY","ATRIA","AUGHT","AURAE","AURAR","AURAS","AURES","AURIC",
  "AVOWS","AWING","AXILS","AXION","AYAHS","AYINS",
  "BABUL","BAFFY","BAITS","BANGS","BARBS","BARDS","BARON","BATES","BATON","BATTY",
  "BAZAR","BEADS","BEADY","BEAUS","BIGOT","BITTY","BLABS","BLIPS","BLOBS","BLOGS",
  "BOAST","BOGIE","BOGUS","BOLTS","BONNY","BONZE","BOOBY","BOOZE","BOTCH","BOUGH",
  "BRAID","BREAM","BREVE","BRIAR","BRIER","BRILL","BRIMS","BRINE","BRINY","BUGLE",
  "BURNS","BUSBY","BUTTS",
  "CACHE","CADET","CALYX","CARVE","CHASM","CHEEP","CHELP","CINCH","CLACK","CLANG",
  "CLANK","CLAPS","CLEAT","CLINK","CLOAK","CLOPS","CLOUT","CLUCK","CLUED","CLUES",
  "CLUNK","COBLE","COBBY","CODEX","CODON","COILS","COLBY","COMBS","COPSE","CORPS",
  "COSET","COXES","CREEL","CREPE","CRUMP","CULPA","CUMIN","CUPPA","CUSHY","CUTUP",
  "DAFFY","DAIRY","DAUNT","DELTA","DICEY","DILLY","DINGY","DIPPY","DIVAN","DIVVY",
  "DOLLY","DOMED","DOPER","DORMY","DOTTY","DOWRY","DROIT","DROOL","DROOP","DRUID",
  "ECLAT","EDIFY","EGADS","EKING","ELEGY","EMEND","EMIRS","EMITS","EMOTE","EVOKE",
  "EXHORT","EXUDE",
  "FADOS","FAERY","FAKIR","FANNY","FARCE","FEMUR","FICUS","FILMY","FINNY","FLECK",
  "FLUFF","FLUKE","FOAMY","FOGGY","FOLIO","FOLLY","FRUGAL","FUROR",
  "GECKO","GILDS","GNASH",
  "HALVE","HANDY","HIKED","HIKER",
  "ICIER","INEPT","INFER","INFIX","INLAY","INTER","INTRO",
  "JADED",
  "KAPPA","KARMA",
  "MALTS","MASSE","MERITORIOUS","MIDWAY","MONGER",
  "NONCE","NUBBY","NUTTY",
  "OFFAL","ORATE",
  "PAMPA","PAPAL","PAROL","PATLY","PAYEE","PEDAL","PIKED","PIPIT","PLAID","PLAIT",
  "PLASM","PLONK","PLOPS","PODGY","POKEY","POLKA","POUTY","PUDGY","PUFFY","PYGMY",
  "QUAFF",
  "RAJAH","RANDY","REEDY","REPEL","RETRY","RETRO","RHYME","RIGID","ROWEL","RUBBY",
  "RUGBY","RUNNY",
  "SALLY","SCREE","SEEPY","SERGE","SHADY","SHAGGY","SHAKY","SHRUB","SHUCK","SHUNT",
  "SISSY","SKIVY","SLANGY","SLEPT","SLICK","SLINK","SLUNK","SLURP","SMOCK","SNAKY",
  "SOOTY","SPATULA","SPIEL","SPINY","SPLAT","SPRIG","SPUNK","STAVE","STEAK","STEED",
  "STOKE","STOMP","STOOP","STRUT","STUMP","SUAVE","SULKY","SURLY","SWILL",
  "TACKY","TAFFY","TALON","TEPID","THATCH","THICK","THONG","TODDY","TOPAZ","TOPIC",
  "TOWEL","TROMP","TROTH","TUBBY","TUBER","TUMMY","TURBO","TWERP","TWINE","TWITCH",
  "UNWED","UPEND","UPPER","UVULA",
  "VAPID","VENOM","VISOR",
  "WADDY","WAFER","WAFTY","WAGER","WAKEN","WARTY","WASPY","WEEDY","WELCH","WENCH",
  "WHACK","WHIRL","WHISK","WISPY","WOOZY","WORDY",
  "YUMMY",
  "ZAPPY","ZLOTY","ZOMBI","ZONAL","ZONK",
]

// Deduplicated, validated answer words
const ANSWER_WORDS_FINAL = [...new Set(
  ANSWER_WORDS.filter(w => w && /^[A-Z]{5}$/.test(w.trim()))
)]

// Full valid guesses = answers + extras, deduplicated
const ALL_VALID_ARRAY = [...new Set([
  ...ANSWER_WORDS_FINAL,
  ...EXTRA_VALID.filter(w => w && /^[A-Z]{5}$/.test(w.trim()))
])]

const VALID_WORDS = new Set(ALL_VALID_ARRAY)

module.exports = { ANSWER_WORDS: ANSWER_WORDS_FINAL, VALID_WORDS }